use_frameworks!

platform :ios, '8.0'

target 'ZZCalendarEventStore_Example' do
  pod 'ZZCalendarEventStore', :path => '../'

  target 'ZZCalendarEventStore_Tests' do
    inherit! :search_paths

    
  end
end
